### ISSUE TITLE
Submit file have error!

### ISSUE THREAD

**Issue by haoshuai714** [adrianofragomeni/MI-MM#1]
I trained and tested against the readme file, but I got the following error in the result file:

WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/pandas/io/pickle.py", line 166, in try_read
    return read_wrapper(lambda f: pkl.load(f))
  File "/opt/conda/lib/python3.7/site-packages/pandas/io/pickle.py", line 148, in read_wrapper
    return func(f)
  File "/opt/conda/lib/python3.7/site-packages/pandas/io/pickle.py", line 166, in 
    return read_wrapper(lambda f: pkl.load(f))
ValueError: unsupported pickle protocol: 5

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/pandas/io/pickle.py", line 173, in try_read
    lambda f: pc.load(f, encoding=encoding, compat=False))
  File "/opt/conda/lib/python3.7/site-packages/pandas/io/pickle.py", line 148, in read_wrapper
    return func(f)
  File "/opt/conda/lib/python3.7/site-packages/pandas/io/pickle.py", line 173, in 
    lambda f: pc.load(f, encoding=encoding, compat=False))
  File "/opt/conda/lib/python3.7/site-packages/pandas/compat/pickle_compat.py", line 227, in load
    return up.load()
  File "/opt/conda/lib/python3.7/pickle.py", line 1085, in load
    dispatch[key[0]](self)
  File "/opt/conda/lib/python3.7/pickle.py", line 1104, in load_proto
    raise ValueError("unsupported pickle protocol: %d" % proto)
ValueError: unsupported pickle protocol: 5

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/pandas/io/pickle.py", line 179, in read_pickle
    return try_read(path)
  File "/opt/conda/lib/python3.7/site-packages/pandas/io/pickle.py", line 177, in try_read
    lambda f: pc.load(f, encoding=encoding, compat=True))
  File "/opt/conda/lib/python3.7/site-packages/pandas/io/pickle.py", line 148, in read_wrapper
    return func(f)
  File "/opt/conda/lib/python3.7/site-packages/pandas/io/pickle.py", line 177, in 
    lambda f: pc.load(f, encoding=encoding, compat=True))
  File "/opt/conda/lib/python3.7/site-packages/pandas/compat/pickle_compat.py", line 227, in load
    return up.load()
  File "/opt/conda/lib/python3.7/pickle.py", line 1085, in load
    dispatch[key[0]](self)
  File "/opt/conda/lib/python3.7/pickle.py", line 1104, in load_proto
    raise ValueError("unsupported pickle protocol: %d" % proto)
ValueError: unsupported pickle protocol: 5

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/pandas/io/pickle.py", line 166, in try_read
    return read_wrapper(lambda f: pkl.load(f))
  File "/opt/conda/lib/python3.7/site-packages/pandas/io/pickle.py", line 148, in read_wrapper
    return func(f)
  File "/opt/conda/lib/python3.7/site-packages/pandas/io/pickle.py", line 166, in 
    return read_wrapper(lambda f: pkl.load(f))
ValueError: unsupported pickle protocol: 5

During handling of the above exception, another exception occurred:
I have train and test as the readme file. But, I have submit test result file in the website has a error as the follow:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/pandas/io/pickle.py", line 173, in try_read
    lambda f: pc.load(f, encoding=encoding, compat=False))
  File "/opt/conda/lib/python3.7/site-packages/pandas/io/pickle.py", line 148, in read_wrapper
    return func(f)
  File "/opt/conda/lib/python3.7/site-packages/pandas/io/pickle.py", line 173, in 
    lambda f: pc.load(f, encoding=encoding, compat=False))
  File "/opt/conda/lib/python3.7/site-packages/pandas/compat/pickle_compat.py", line 227, in load
    return up.load()
  File "/opt/conda/lib/python3.7/pickle.py", line 1085, in load
    dispatch[key[0]](self)
  File "/opt/conda/lib/python3.7/pickle.py", line 1104, in load_proto
    raise ValueError("unsupported pickle protocol: %d" % proto)
ValueError: unsupported pickle protocol: 5

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/codalab/tmpdmdqkK/run/program/epic_challenges/multi_instance_retrieval_challenge.py", line 144, in 
    main(parser.parse_args())
  File "/tmp/codalab/tmpdmdqkK/run/program/epic_challenges/multi_instance_retrieval_challenge.py", line 116, in main
    submission = pd.read_pickle(results_dir / "test.pkl")
  File "/opt/conda/lib/python3.7/site-packages/pandas/io/pickle.py", line 182, in read_pickle
    return try_read(path, encoding='latin1')
  File "/opt/conda/lib/python3.7/site-packages/pandas/io/pickle.py", line 177, in try_read
    lambda f: pc.load(f, encoding=encoding, compat=True))
  File "/opt/conda/lib/python3.7/site-packages/pandas/io/pickle.py", line 148, in read_wrapper
    return func(f)
  File "/opt/conda/lib/python3.7/site-packages/pandas/io/pickle.py", line 177, in 
    lambda f: pc.load(f, encoding=encoding, compat=True))
  File "/opt/conda/lib/python3.7/site-packages/pandas/compat/pickle_compat.py", line 227, in load
    return up.load()
  File "/opt/conda/lib/python3.7/pickle.py", line 1085, in load
    dispatch[key[0]](self)
  File "/opt/conda/lib/python3.7/pickle.py", line 1104, in load_proto
    raise ValueError("unsupported pickle protocol: %d" % proto)
ValueError: unsupported pickle protocol: 5

**Comment by adrianofragomeni** [comment]
HI,

Try to exchange all `import pickle` with `import pickle5 as pickle`.
In this way, you should be able to read a pickle file with protocol 5.

**Comment by haoshuai714** [comment]
Thanks!

**Comment by haoshuai714** [comment]
Thanks!

**Comment by haoshuai714** [comment]
I have exchange import pickle to import pickle5 as pickle. And,  I use python 3.7, but I always has this error. Please cheack if your  challenge system with problem?

**Comment by adrianofragomeni** [comment]
Hello,

Can you give me more details when you get this error?
What python code did you run?
Do you have the error running the MI-MM code  or when you submit the results on the challenge system?

Thank you

Adriano


Adriano Fragomeni
PhD Student in Computer Vision
Department of Computer Science
University of Bristol
https://adrianofragomeni.github.io<https://adrianofragomeni.github.io/>
________________________________

**Comment by adrianofragomeni** [comment]
Can you give me more details when you get this error?
What python code did you run?
Do you have the error running the MI-MM code  or when you submit the results to the challenge system?

**Comment by haoshuai714** [comment]
I have deal with this error. It is the problem of pickle protocol.
